---
name: Hello world workflow

on:
 push:
   branches: 
   - main
pull_requests:
  branches:
  - main
workflow_dispatch: 

jobs:
  hello:
    run-on: ubuntu-latest
    steps:
      - uses: actions/cheeckout@v2
      - name: "Hello world"
        shell: bash
goodbye:
  runs-on: ubuntu-latests
  steps:
  - name: goodyboye
    run: echo "helloe word "
    shell: bash
