name: Hello world workflow

on:
 push:
   branches: 
   - main
pull_request:
  branches:
  - main
workflow_dispatch: 

jobs:
  hello:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world
        run: echo "hello word "
        shell: bash
goodbye:
  runs-on: ubuntu-latests
  steps:
  - name: goodyboye
    run: echo "hello word "
    shell: bash
